apiVersion: v1
kind: Service
metadata:
  name: newpython-service
  namespace: default
spec:
  selector:
    app: quote
  type: NodePort # Adjust type as needed (e.g., NodePort)
  ports:
  - protocol: TCP
    port: 80 # Adjust port if needed
    targetPort: 80 #Container Port